# Generated by Django 4.1.7 on 2025-02-02 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0002_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TECH', 'Tech'), ('CLOTHING', 'Clothing'), ('FOOD', 'Food'), ('FURNITURE', 'Furniture'), ('BEAUTY', 'Beauty'), ('SPORTS', 'Sports'), ('AUTOMOTIVE', 'Automotive'), ('TOYS', 'Toys'), ('BOOKS', 'Books'), ('MUSIC', 'Music'), ('HEALTH', 'Health'), ('HOME_APPLIANCES', 'Home Appliances'), ('GROCERY', 'Grocery'), ('JEWELRY', 'Jewelry'), ('PET_SUPPLIES', 'Pet Supplies'), ('ELECTRONICS', 'Electronics'), ('BABY_PRODUCTS', 'Baby Products'), ('GARDENING', 'Gardening'), ('OFFICE_SUPPLIES', 'Office Supplies'), ('TRAVEL', 'Travel'), ('OUTDOOR', 'Outdoor & Camping'), ('VIDEO_GAMES', 'Video Games'), ('HANDMADE', 'Handmade & Crafts'), ('LUXURY', 'Luxury Items'), ('MEDICAL', 'Medical & Pharmacy'), ('INDUSTRIAL', 'Industrial & Tools'), ('GIFTS', 'Gifts & Collectibles'), ('MOVIES', 'Movies & Entertainment'), ('HOME_DECOR', 'Home Decor'), ('ART', 'Art & Paintings'), ('HOBBIES', 'Hobbies & DIY'), ('SECURITY', 'Security & Surveillance'), ('BICYCLES', 'Bicycles & Accessories'), ('WATCHES', 'Watches'), ('FARMING', 'Farming & Agriculture'), ('REAL_ESTATE', 'Real Estate'), ('EDUCATION', 'Education & e-Learning'), ('GAMING', 'Gaming'), ('FASHION', 'Fashion'), ('SPIRITUAL', 'Spiritual & Religious'), ('MOTORS', 'Motorcycles & Scooters'), ('RESTAURANTS', 'Restaurants & Cafes'), ('BAKERY', 'Bakery & Confectionery'), ('WEDDINGS', 'Weddings & Events'), ('PHOTOGRAPHY', 'Photography & Videography'), ('MUSICAL_INSTRUMENTS', 'Musical Instruments'), ('TEA_COFFEE', 'Tea & Coffee'), ('FISHING', 'Fishing & Hunting'), ('DRONES', 'Drones & RC Gadgets'), ('ENERGY', 'Solar & Renewable Energy'), ('VR_AR', 'VR & AR Equipment'), ('FITNESS', 'Fitness & Gym Equipment')], max_length=50)),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.CharField(choices=[('TECH', 'Tech'), ('CLOTHING', 'Clothing'), ('FOOD', 'Food'), ('FURNITURE', 'Furniture'), ('BEAUTY', 'Beauty'), ('SPORTS', 'Sports'), ('AUTOMOTIVE', 'Automotive'), ('TOYS', 'Toys'), ('BOOKS', 'Books'), ('MUSIC', 'Music'), ('HEALTH', 'Health'), ('HOME_APPLIANCES', 'Home Appliances'), ('GROCERY', 'Grocery'), ('JEWELRY', 'Jewelry'), ('PET_SUPPLIES', 'Pet Supplies'), ('ELECTRONICS', 'Electronics'), ('BABY_PRODUCTS', 'Baby Products'), ('GARDENING', 'Gardening'), ('OFFICE_SUPPLIES', 'Office Supplies'), ('TRAVEL', 'Travel'), ('OUTDOOR', 'Outdoor & Camping'), ('VIDEO_GAMES', 'Video Games'), ('HANDMADE', 'Handmade & Crafts'), ('LUXURY', 'Luxury Items'), ('MEDICAL', 'Medical & Pharmacy'), ('INDUSTRIAL', 'Industrial & Tools'), ('GIFTS', 'Gifts & Collectibles'), ('MOVIES', 'Movies & Entertainment'), ('HOME_DECOR', 'Home Decor'), ('ART', 'Art & Paintings'), ('HOBBIES', 'Hobbies & DIY'), ('SECURITY', 'Security & Surveillance'), ('BICYCLES', 'Bicycles & Accessories'), ('WATCHES', 'Watches'), ('FARMING', 'Farming & Agriculture'), ('REAL_ESTATE', 'Real Estate'), ('EDUCATION', 'Education & e-Learning'), ('GAMING', 'Gaming'), ('FASHION', 'Fashion'), ('SPIRITUAL', 'Spiritual & Religious'), ('MOTORS', 'Motorcycles & Scooters'), ('RESTAURANTS', 'Restaurants & Cafes'), ('BAKERY', 'Bakery & Confectionery'), ('WEDDINGS', 'Weddings & Events'), ('PHOTOGRAPHY', 'Photography & Videography'), ('MUSICAL_INSTRUMENTS', 'Musical Instruments'), ('TEA_COFFEE', 'Tea & Coffee'), ('FISHING', 'Fishing & Hunting'), ('DRONES', 'Drones & RC Gadgets'), ('ENERGY', 'Solar & Renewable Energy'), ('VR_AR', 'VR & AR Equipment'), ('FITNESS', 'Fitness & Gym Equipment')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.stores')),
            ],
        ),
    ]
