# Generated by Django 4.1.7 on 2025-02-04 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0006_checkoutmodel_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutmodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('shipping_address', models.TextField()),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='Shop.products')),
            ],
        ),
    ]
