# Generated by Django 4.1.7 on 2025-02-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_remove_checkoutmodel_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutmodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
