# Generated by Django 4.1.7 on 2025-02-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_checkoutmodel_slug_checkoutmodel_tracking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutmodel',
            name='slug',
            field=models.SlugField(blank=True, default='default_slug_value', unique=True),
        ),
    ]
