# Generated by Django 4.1.7 on 2025-02-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_alter_checkoutmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutmodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
