# Generated by Django 4.1.7 on 2025-02-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_alter_checkoutmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('in_warehouse', 'IN OUR WAREHOUSE'), ('in_your_city', 'IN YOUR CITY'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
