# Generated by Django 4.1.7 on 2025-02-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='image',
            field=models.ImageField(default=5, upload_to='Store_Images/'),
            preserve_default=False,
        ),
    ]
