# Generated by Django 4.1.7 on 2025-02-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_stores_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='unique_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
